name: Test Template

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    # container:
    #   image: ubuntu:jammy
    steps:
      - name: Install ROS 2 Humble Packages
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository universe
          sudo apt update && sudo apt install -y curl
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
          sudo apt update
          sudo apt install -y ros-humble-ros-base python3-colcon-common-extensions
          sudo apt install -y lcov

      - name: Setup Workspace
        run: |
          source /opt/ros/humble/setup.bash
          mkdir -p ros_ws/src/slam_traffic
          cd ros_ws
          colcon build
          source install/setup.bash

      - uses: actions/checkout@v4
        with:
          path: ros_ws/src/slam_traffic

      - name: Install Dependencies
        run: |
          source /opt/ros/humble/setup.bash
          sudo apt install python3-rosdep
          sudo rosdep init
          rosdep update
          cd ros_ws
          rosdep install -y --from-paths src --ignore-src
          colcon build --packages-select slam_traffic
          source install/setup.bash

      - name: Run Tests
        run: |
          source /opt/ros/humble/setup.bash
          source ros_ws/install/setup.bash
          cd ros_ws
          colcon test --packages-select slam_traffic
          colcon test-result --verbose --all

